---
title: "Sophia's Mastersite for Data Projects"
description: |
  Collection of my data projects 
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

## Hello!

Hi, I’m Sophia! I’m a student at the University of Waterloo and Wilfrid Laurier University, currently pursing a double degree in BMath and BBA. This website is going to aggregate the data projects that I have in one space! 

These data projects are mainly a way to: 

a) Improve my R programming skills. 
b) Explore a niche that interests me!

These objectives become more specific when you click onto the projects (click the tabs on the top right!) as I always have certain goals I want to achieve. But, I started (and continue) to work with data because it's super interesting to see how you can transform a mess of numbers into meaningful insights through analysis - and see how these insights can result in vital changes! The continual process to discover the 'truth' of the data set is incredibly rewarding and encourages me to delve further into data science.  

If you have any questions about my projects or would like to reach out, please contact me [here](mailto:iceyes123@gmail.com)! You can also learn more about me on my website: <a target="_blank" rel="noopener" href="www.zhusophia.github.io">zhusophia.github.io.</a>