---
title: "Analyzing Big Five Personality Test Results"
description: |
  The Internet, it turns out, is NOT a microcosm for society. 
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

## Introduction 

NOTICE: This project is currently a work-in-progress. The data analysis and introduction are finished, however, further research is not. I'll be continuously adding various bits and pieces, and you'll absolutely encounter awkward sentences + spelling/grammar mistakes. Welcome to the slow process of analysis, and enjoy your stay (while it lasts)! 


## Welcome!

You might be thinking: Sophia, Why are you even dabbling in psych if you're studying math and business? Well, it's simple: I find people (and subsequently, how they act) incredibly fascinating. They allow me to explore different perspectives and it's a really great way of knowing what you don't know. Not only that, but it's so interesting to pick apart WHY people do/believe things  -- everybody has a nuanced reason for their actions, built from a unique mosaic of personal experiences, beliefs, and values. 

When I talk to people, I try to glean as much as I can, creating an image of who they are in my mind. Then, like every other human, proceed to analyze and judge them. Based on what traits they've shown, I reference my past experiences with similar people to figure out what interests they might have, whether I'd enjoy being friends with them, or how their personality came to be!

The Big Five's personality system helps with this process, as it compartmentalizes people into distinct and specific groups. It breaks people down into five fundamental traits, and based on these, you can make assumptions on what they're like. I personally don't use the Big Five system to categorize people, but it's still interesting to delve into it and see the groups we split ourselves into. 

Hence, this data project isn't just a way for me to brush up on my R skills. It's a combination of exploring of general human personalities, as told by the Big Five system, and analyzing why the data shows the results it does. Or, it's a little introduction into psychology and our internal biases, as well as a dash of geography and various other facts I recall when writing this piece! You can even consider it a fun little side-quest to end off my first year. 

Regardless, at this moment in time, this project will be an analysis of Big Five Personality Test results. The raw data was collected by <a href="https://openpsychometrics.org/" target="_blank">Open Psychometrics</a>, containing over 1 million responses from hundreds of different countries. Data was collected with consent from the user.   

If you’re interested in a specific part, you may skip ahead: 

**Introduction**

1. [Personal Objectives](#Objectives)
2. [What is the Big Five (SLOAN)](#SLOAN)
3. [Discussing Data](#ddata) 

**Data**

4. [What is the most popular result? ](fivedata.html#popres)
5. [Do results vary between countries?](fivedata.html#country) 
6. [Are all questions created equal?](fivedata.html#questions)

**Further Analysis** 

7. Limitations of Big Five 
8. Connection of Big Five and Daily Life

### Personal Objectives <a name="Objectives"></a>

After looking at the raw data, a few questions stood out to me: 

1. What are the actual results of the data? Which results were the most popular? 
2. Did these results vary between different countries? How do countries compare against one another? 
3. How did users react to questions? Was there standard distribution? Did people spend more time on one question compared to another? 
4. Why did this quiz get the results that it did? Why are people the way they are? 
5. What does the Big Five actually tell us? How can people incorporate it into their daily lives and use it to improve themselves? 

Questions 1 through 3 are pretty data-based as the answers lie somewhere within the raw data, allowing me to hone my skills of cleaning, manipulating, and visualizing data. Question 4, on the other hand, is far more speculation alongside slight research, where I draw from my experiences and Google's knowledge to form an answer. 

Question 5 also allows me to explore the Big Five personality model based on my own interests. I want to see the underlying psychological principals and insights the Big Five provides, and how I can apply it to my daily life. Hence, I'll be spending some  time analyzing the system and understanding the concept as a whole. Together, these objectives make this project an enjoyable challenge to tackle. 

But, let's take a detour from answering the above questions and establish the following: 

### What is the Big Five (SLOAN) <a name="SLOAN"></a>

The Big Five is a personality model that categories people with 5 major personality traits: 

* *Extroversion* - Sociable / Reserved 
  * How outgoing are you? 
* *Neuroticism* - Calm / Limbic
  * How emotionally stable are you? 
* *Conscientiousness* -  Organized / Unstructured 
  * Can you motivate yourself to diligently complete work?   
* *Agreeableness* - Agreeable / Egocentric 
  * Are you willing to compromise your needs for others? Do you get along well with others? 
* *Openness* - Inquisitive / Non-inquisitive (to new experiences)
  * Do you prefer familiarity? Is aesthetic important to you? 

These five major traits can be broken down further. For example, extroversion contains 6 'faucets' like gregariousness, assertiveness, and excitement-seeking, and these faucets help you better understand what this test analyzes in regards to 'extrovertedness'. However, faucets are  beyond the scope of this investigation. More information can be found<a href="https://www.mindintertwined.com/blog/big-five-personality-traits-extroversion" target="_blank"> here.</a>

To get your results, you determine which 'letter' you are for each category (e.g. If you're *more* social than reserved, then you'd say that you're an 'S'),^[Note that you're only looking for which side you identify with more. You're never ONLY going to be social or ONLY reserved. Human behaviour exists on a spectrum.] then combine your letters from all the categories together. For example, a possible result is RLOEN, standing for reserved, limbic, organized, egocentric and non-inquisitive. This can be seen by looking at the first letter of each trait. 

However, if you really can't decide what you are, another possibility is replacing letters with an 'X'. For example, this can be seen in the potential combination of SXUAN. The 'X' in the neuroticism (2nd) slot means that you're in between calm and limbic, as you exhibit both traits equally and there is no 'conclusive' answer. However, it is extremely likely for people to identify with one side *slightly* more than the other, so having 'X' (denoting that you're perfectly in between) should not be a common occurrence.^[You'll actually see a surprising number of respondents have an 'X' in their results in this data set. However, I really do believe that people always lean more to one trait more than another, and you'll only receive an 'X' if you take a self-administered quiz -- after all, we're trying to compute humans and that will never result in a completely holistic judgement.]   
I'm using SLOAN formatting (i.e. Letters will be in the order of extroversion, neuroticism, conscientiousness, agreeableness, and openness) and will use the above wording (i.e. Agreeableness, Neuroticism) to describe the Big Five traits throughout the investigation. If you decide to do your own research, you'll likely see others using the CANOE or OCEAN formatting/use different words to describe the traits. 

Interested in what your results are? The Open Psychometrics Big Five quiz can be <a href="https://openpsychometrics.org/tests/IPIP-BFFM/" target="_blank">taken here.</a>
  
**Citations**

* <a href="https://en.wikipedia.org/wiki/Big_Five_personality_traits" target="_blank">https://en.wikipedia.org/wiki/Big_Five_personality_traits</a>
* <a href="https://similarminds.com/sloan.html" target="_blank">https://similarminds.com/sloan.html</a>


### Discussing Data <a name="ddata"></a>
This quiz is self-administered, with 1,015,342 respondents answering 50 questions over ~2 years. Since we have 50 questions, this means that there were 10 questions correlated with each personality trait. 

Every question used a Likert scale (i.e. a 5 point scale) with 1 meaning "I disagree with the prompt", 3 meaning "I am neutral on the prompt", and 5 meaning "I agree with the prompt".  

Some sample prompts include: 

* I don't mind being the center of attention. (Testing extrovertism) 
* I have frequent mood swings. (Testing neuroticism) 
* I do not have a good imagination. (Testing openness) 

You can find all the questions <a href="https://ipip.ori.org/newBigFive5broadKey.htm" target="_blank">here</a>, if you look at all the 10-item scale questions. 

Every respondent received the questions in the same questions, in the same order. However, the questions were displayed in a specific order, with questions following the pattern of Extroversion Q1, Agreeableness Q1, Conscientiousness Q1, Neuroticism Q1, Openness Q1, then moving onto Extroversion Q2, Agreeableness Q2, etc. Each rotation will be called a 'round', with 10 rounds in total.

### Congrats! You've received a run-down of all the admin/context stuff!

Next: [Explore the Data](fivedata.html)